const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);
const labels=["Frente","Traseira","Lateral esquerda","Lateral direita","Interior/Painel","Extra"];
let currentPhotos=[],activePhoto=null,pendingPoint=null,editingId=null,editingSignaturePath=null;
const online=document.getElementById("online");
const sign=document.getElementById("sign"),ctx=sign.getContext("2d");

async function boot(){const {error}=await sb.from("checklists").select("id").limit(1);online.textContent=error?"Offline / erro de conexão":"Online • Supabase conectado";novoChecklist()}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");if(id==="lista")renderLista()}
function novoChecklist(){editingId=null;editingSignaturePath=null;show("novo");resetForm()}
async function resetForm(){currentPhotos=[];document.getElementById("photos").innerHTML="";labels.forEach((x,i)=>addPhotoSlot(x,i));clearSign();setFields({});document.getElementById("osNum").textContent="...";document.getElementById("formTitle").textContent="Novo checklist";document.getElementById("saveBtn").textContent="Finalizar checklist";const {data,error}=await sb.rpc("next_checklist_os");document.getElementById("osNum").textContent=error?"automática":String(data).padStart(4,"0")}
function setFields(c){document.getElementById("funcionario").value=c.funcionario||"";document.getElementById("cliente").value=c.cliente||"";document.getElementById("telefone").value=c.telefone||"";document.getElementById("veiculo").value=c.veiculo||"";document.getElementById("placa").value=c.placa||"";document.getElementById("km").value=c.km||"";document.getElementById("servico").value=c.servico||"";document.getElementById("obs").value=c.observacoes||"";document.querySelectorAll(".checks input").forEach(x=>x.checked=(c.itens_internos||[]).includes(x.value))}
function addPhotoSlot(label,i){const d=document.createElement("div");d.className="photo";d.innerHTML=`<input type="file" accept="image/*" capture="environment"><div class="cap">${label}</div>`;d.querySelector("input").onchange=()=>handlePhoto(d.querySelector("input").files[0],i,label);document.getElementById("photos").appendChild(d)}
function handlePhoto(file,i,label){if(!file)return;const r=new FileReader();r.onload=()=>{currentPhotos[i]={label,data:r.result,file,marks:[]};renderPhoto(i)};r.readAsDataURL(file)}
function renderPhoto(i){const p=currentPhotos[i],slot=document.getElementById("photos").children[i];if(!p)return;slot.innerHTML=`<img src="${p.data}"><div class="cap">${p.label} · toque para marcar</div><div class="marks">${p.marks.map(m=>`<span class="dot" style="left:${m.x}%;top:${m.y}%"></span>`).join("")}</div>`;slot.onclick=()=>openModal(i)}
function openModal(i){if(!currentPhotos[i])return;activePhoto=i;pendingPoint=null;document.getElementById("modalImg").src=currentPhotos[i].data;document.getElementById("desc").value="";document.getElementById("markers").innerHTML=currentPhotos[i].marks.map(m=>`<span class="dot" style="left:${m.x}%;top:${m.y}%"></span>`).join("");document.getElementById("modal").classList.remove("hidden");document.getElementById("modal").style.display="flex";const img=document.getElementById("modalImg");img.onclick=e=>{const r=img.getBoundingClientRect();pendingPoint={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};document.getElementById("markers").innerHTML=currentPhotos[i].marks.map(m=>`<span class="dot" style="left:${m.x}%;top:${m.y}%"></span>`).join("")+`<span class="dot" style="left:${pendingPoint.x}%;top:${pendingPoint.y}%"></span>`}}
function salvarMarca(){if(!pendingPoint)return alert("Toque no ponto da avaria.");currentPhotos[activePhoto].marks.push({x:pendingPoint.x,y:pendingPoint.y,type:document.getElementById("tipo").value,desc:document.getElementById("desc").value});renderPhoto(activePhoto);fecharModal()}
function fecharModal(){const m=document.getElementById("modal");m.classList.add("hidden");m.style.display="none"}
function clearSign(){ctx.clearRect(0,0,sign.width,sign.height)}
let drawing=false;function pos(e){const r=sign.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*sign.width/r.width,y:(p.clientY-r.top)*sign.height/r.height}}function start(e){drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){drawing=false}
sign.addEventListener("mousedown",start);sign.addEventListener("mousemove",move);window.addEventListener("mouseup",end);sign.addEventListener("touchstart",start);sign.addEventListener("touchmove",move);window.addEventListener("touchend",end);

async function uploadBlob(blob,path){const {error}=await sb.storage.from("checklist-files").upload(path,blob,{upsert:true,contentType:blob.type||"image/jpeg"});if(error)throw error;return path}
async function dataUrlToBlob(url){const r=await fetch(url);return await r.blob()}
function signatureHasInk(){return ctx.getImageData(0,0,sign.width,sign.height).data.some(v=>v!==0)}
function formData(){return {funcionario:document.getElementById("funcionario").value.trim(),cliente:document.getElementById("cliente").value.trim(),telefone:document.getElementById("telefone").value,veiculo:document.getElementById("veiculo").value,placa:document.getElementById("placa").value.trim().toUpperCase(),km:document.getElementById("km").value,servico:document.getElementById("servico").value,observacoes:document.getElementById("obs").value,itens_internos:[...document.querySelectorAll(".checks input:checked")].map(x=>x.value)}}
async function finalizar(){if(editingId)return salvarEdicao();const d=formData();if(!d.funcionario||!d.cliente||!d.placa)return alert("Preencha funcionário, cliente e placa.");const {data:check,error}=await sb.from("checklists").insert({...d,status:"finalizado",finalized_at:new Date().toISOString()}).select().single();if(error)return alert("Erro ao salvar OS: "+error.message);try{await salvarArquivos(check.id,false);alert(`Checklist OS ${String(check.os_num).padStart(4,"0")} salvo online!`);show("lista")}catch(e){alert("A OS foi criada, mas houve erro ao enviar algum arquivo: "+e.message)}}
async function salvarArquivos(id,editMode){for(const p of currentPhotos.filter(Boolean)){let photoId=p.id,storagePath=p.storage_path;if(p.file){const ext=(p.file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"").toLowerCase()||"jpg";storagePath=`${id}/${p.id?`foto-${p.id}`:crypto.randomUUID()}.${ext}`;await uploadBlob(p.file,storagePath);if(p.id){const {error:ue}=await sb.from("checklist_photos").update({storage_path:storagePath}).eq("id",p.id);if(ue)throw ue}else{const {data:photo,error:pe}=await sb.from("checklist_photos").insert({checklist_id:id,categoria:p.label,storage_path:storagePath}).select().single();if(pe)throw pe;photoId=photo.id;p.id=photoId}}
 if(!photoId)continue;
 if(editMode){const {error:de}=await sb.from("checklist_marks").delete().eq("photo_id",photoId);if(de)throw de}
 for(const m of p.marks){const {error:me}=await sb.from("checklist_marks").insert({photo_id:photoId,x:m.x,y:m.y,tipo:m.type,descricao:m.desc});if(me)throw me}
}
 if(signatureHasInk()){const blob=await new Promise(r=>sign.toBlob(r,"image/png"));await uploadBlob(blob,`${id}/assinatura.png`);const {error}=await sb.from("checklists").update({assinatura_path:`${id}/assinatura.png`}).eq("id",id);if(error)throw error}
}
async function renderLista(){const q=(document.getElementById("busca").value||"").trim();let query=sb.from("checklists").select("*").order("created_at",{ascending:false});if(q)query=query.or(`cliente.ilike.%${q}%,placa.ilike.%${q}%,funcionario.ilike.%${q}%`);const {data,error}=await query;const box=document.getElementById("listaBox");if(error){box.innerHTML=`<p>Erro: ${error.message}</p>`;return}box.innerHTML=data.length?data.map(x=>`<div class="item"><div class="itemInfo"><div class="itemTitle"><b>OS ${String(x.os_num).padStart(4,"0")}</b><span class="status">Finalizado</span></div><div class="itemClient">${esc(x.cliente||"Sem cliente")}</div><small>${esc(x.veiculo||"")} ${x.placa?`· ${esc(x.placa)}`:""} ${x.funcionario?`· ${esc(x.funcionario)}`:""}</small></div><div class="itemActions"><button class="viewBtn" onclick="abrir(${JSON.stringify(x.id)})">👁 Visualizar</button><button class="editBtn" onclick="editarChecklist(${JSON.stringify(x.id)})">✎ Editar</button></div></div>`).join(""):"<p class='muted'>Nenhum checklist encontrado.</p>"}
async function abrir(id){const {data:c,error:ce}=await sb.from("checklists").select("*").eq("id",id).single();if(ce)return alert("Erro ao abrir OS: "+ce.message);const {data:photos,error:pe}=await sb.from("checklist_photos").select("*").eq("checklist_id",id).order("created_at",{ascending:true});if(pe)return alert("Erro ao carregar fotos: "+pe.message);const ids=(photos||[]).map(p=>p.id);let marks=[];if(ids.length){const r=await sb.from("checklist_marks").select("*").in("photo_id",ids);marks=r.data||[]}
let html=`<div class="detailTop"><div><h1>OS ${String(c.os_num).padStart(4,"0")}</h1><p><b>Cliente:</b> ${esc(c.cliente)}<br><b>Telefone:</b> ${esc(c.telefone)||"-"}<br><b>Veículo:</b> ${esc(c.veiculo)||"-"} · <b>Placa:</b> ${esc(c.placa)} · <b>KM:</b> ${esc(c.km)||"-"}<br><b>Funcionário:</b> ${esc(c.funcionario)}<br><b>Serviço:</b> ${esc(c.servico)||"-"}<br><b>Observações:</b> ${esc(c.observacoes)||"-"}</p></div><button class="primary" onclick="editarChecklist('${c.id}')">✎ Editar checklist</button></div><div class="card"><h2>Conferência interna</h2><p>${(c.itens_internos||[]).map(esc).join(" · ")||"Nenhum item marcado."}</p></div><div class="card"><h2>Fotos e avarias</h2><div class="gallery">`;
for(const p of (photos||[])){const {data:u}=sb.storage.from("checklist-files").getPublicUrl(p.storage_path);const pm=marks.filter(m=>m.photo_id===p.id);html+=`<div class="detailPhoto"><div class="photoView"><img src="${u.publicUrl}">${pm.map(m=>`<span class="dot" style="left:${m.x}%;top:${m.y}%"></span>`).join("")}</div><b>${esc(p.categoria)}</b>${pm.map(m=>`<div class="markrow"><b>${esc(m.tipo)}</b> — ${esc(m.descricao)||"sem descrição"}</div>`).join("")}</div>`}html+=`</div></div>`;if(c.assinatura_path){const {data:u}=sb.storage.from("checklist-files").getPublicUrl(c.assinatura_path);html+=`<div class="card"><h2>Assinatura</h2><img class="signatureImg" src="${u.publicUrl}"></div>`}document.getElementById("detalheBox").innerHTML=html;show("detalhe")}
function esc(v){return String(v??"").replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
async function editarChecklist(id){const {data:c,error}=await sb.from("checklists").select("*").eq("id",id).single();if(error)return alert("Erro ao carregar OS: "+error.message);const {data:photos}=await sb.from("checklist_photos").select("*").eq("checklist_id",id).order("created_at",{ascending:true});const ids=(photos||[]).map(p=>p.id);let marks=[];if(ids.length){const r=await sb.from("checklist_marks").select("*").in("photo_id",ids);marks=r.data||[]}
editingId=id;editingSignaturePath=c.assinatura_path||null;currentPhotos=[];document.getElementById("photos").innerHTML="";labels.forEach((x,i)=>{const d=document.createElement("div");d.className="photo";document.getElementById("photos").appendChild(d)});(photos||[]).forEach((p,i)=>{const {data:u}=sb.storage.from("checklist-files").getPublicUrl(p.storage_path);currentPhotos[i]={id:p.id,label:p.categoria,data:u.publicUrl,file:null,storage_path:p.storage_path,marks:marks.filter(m=>m.photo_id===p.id).map(m=>({x:m.x,y:m.y,type:m.tipo,desc:m.descricao}))};renderPhoto(i)});for(let i=(photos||[]).length;i<labels.length;i++)addPhotoSlot(labels[i],i);setFields(c);clearSign();document.getElementById("formTitle").textContent=`Editar checklist • OS ${String(c.os_num).padStart(4,"0")}`;document.getElementById("saveBtn").textContent="Salvar alterações";document.getElementById("osNum").textContent=String(c.os_num).padStart(4,"0");show("novo")}
async function salvarEdicao(){const d=formData();if(!d.funcionario||!d.cliente||!d.placa)return alert("Preencha funcionário, cliente e placa.");const {error}=await sb.from("checklists").update(d).eq("id",editingId);if(error)return alert("Erro ao atualizar OS: "+error.message);try{await salvarArquivos(editingId,true);alert("Alterações salvas com sucesso!");await abrir(editingId)}catch(e){alert("Os dados foram atualizados, mas houve erro ao atualizar arquivos: "+e.message)}}
document.getElementById("busca").addEventListener("input",renderLista);
boot();
